pipeline:
  build:
    image: debian:stretch
    commands:
      - "pwd; ls;\
        apt-get update && apt-get install -y \
        build-essential \
        g++ \
        cmake \
        make \
        git"
      - "apt-get install -y \
        libx11-xcb-dev \
        libglew-dev \
        freeglut3-dev \
        libjpeg-dev \
        libfreetype6-dev \
        libxrandr-dev \
        libglew-dev \
        libsndfile1-dev \
        libopenal-dev \
        libudev-dev \
        default-libmysqlclient-dev \
        mysql-common"
      - "git clone -b 2.4.x https://github.com/SFML/SFML.git sfml; \
        cd sfml; \
        mkdir -p build; \
        cd build; \
        cmake -DCMAKE_BUILD_TYPE=Release ../; \
        make install ."
      - "cd ../../Server; \
        mkdir -p build; \
        cd build; \
        cmake -DCMAKE_BUILD_TYPE=Release ../; \
        make"

  publish_server:
    image: swserver
    repo: pinkmouse
    secrets: [ pinkmouse, Pierro41 ]
    tag: [ latest ]
    when:
      branch: master
